// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_bugtrackerapi.Data;

namespace dotnet_bugtrackerapi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("dotnet_bugtrackerapi.Models.Breakage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreakageReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Breakages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreakageReason = "Timeout Exception",
                            Date = new DateTime(2020, 9, 27, 16, 23, 21, 683, DateTimeKind.Local).AddTicks(2875)
                        },
                        new
                        {
                            Id = 2,
                            BreakageReason = "Stale Element Exception",
                            Date = new DateTime(2020, 9, 27, 16, 23, 21, 683, DateTimeKind.Local).AddTicks(3540)
                        });
                });

            modelBuilder.Entity("dotnet_bugtrackerapi.Models.Fix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BreakageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowFixed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BreakageId")
                        .IsUnique();

                    b.ToTable("Fixes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreakageId = 1,
                            Date = new DateTime(2020, 9, 27, 16, 23, 21, 678, DateTimeKind.Local).AddTicks(4413),
                            HowFixed = "Added wait"
                        },
                        new
                        {
                            Id = 2,
                            BreakageId = 2,
                            Date = new DateTime(2020, 9, 27, 16, 23, 21, 682, DateTimeKind.Local).AddTicks(1284),
                            HowFixed = "Updated CSS Selector"
                        });
                });

            modelBuilder.Entity("dotnet_bugtrackerapi.Models.Fix", b =>
                {
                    b.HasOne("dotnet_bugtrackerapi.Models.Breakage", "Breakage")
                        .WithOne("Fix")
                        .HasForeignKey("dotnet_bugtrackerapi.Models.Fix", "BreakageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
